apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-app-deployment
  namespace: e-store
spec:
  selector:
    matchLabels:
      app: stock-app-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: stock-app-deployment
    spec:
      containers:
        - name: stock-app-container
          image: rso6315/stock-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://stock-db.e-store:5432/stocks
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: postgres
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stock-pass
                  key: POSTGRES_PASSWORD
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stock-service
  name: stock-service
  namespace: e-store
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31014
      targetPort: 8080
      protocol: TCP
  selector:
    app: stock-app-deployment