apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-app-deployment
  namespace: e-store
spec:
  selector:
    matchLabels:
      app: stock-app-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: stock-app-deployment
    spec:
      containers:
        - name: stock-app-container
          image: rso6315/stock-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KUMULUZEE_SERVER_BASE-URL
              value: http://35.246.208.18/stock-service
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: third-cluster
            - name: KUMULUZEE_DISCOVERY_CONSUL_AGENT
              value: http://consul-service-consul-server.e-store:8500
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://consul-service-consul-server.e-store:8500
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://stock-db.e-store:5432/stocks
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: postgres
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stock-pass
                  key: POSTGRES_PASSWORD
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3    
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stock-service
  name: stock-service
  namespace: e-store
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31014
      targetPort: 8080
      protocol: TCP
  selector:
    app: stock-app-deployment
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stock-app-autoscaler
  namespace: e-store
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stock-app-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 30