sudo: required

services:
  - docker

language: java
dist: trusty

branches:
  only:
    - develop
    - master

jdk:
  - openjdk11

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/google-cloud-sdk/"

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME=local-reference-258619
    - CLUSTER_NAME=third-cluster
    - CLOUDSDK_COMPUTE_ZONE=europe-west3-b
    - DOCKER_IMAGE_NAME=rso6315/stock-service
    - KUBE_DEPLOYMENT_NAME=stock-app-deployment
    - KUBE_DEPLOYMENT_CONTAINER=stock-app-container

install: echo "Skipping installation"

script:
  - mvn clean package -DskipTests=true --settings .ci/settings.xml
  - docker build -t rso6315/stock-service .

after_success:
  - mvn deploy -DskipTests=true --settings .ci/settings.xml -P !default,deploy-lib
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push rso6315/stock-service

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: bash ./.ci/deploy.sh
    skip_cleanup: true
    on:
      branch: master

notifications:
  email: false
  slack:
    rooms:
      - rso-6315:GemkjD1zzD1AAKrXCrn9LUC3
    on_success: always
    on_failure: always
    template:
      - "`%{result}` build for repo `%{repository_slug}` on branch `%{branch}`. Build (<%{build_url}|#%{build_number}>). Commit (<%{compare_url}|%{commit}>)."
      - "Execution time: *%{duration}*"
      - "Message: *%{message}*"

